### ISSUE TITLE
Disable autolink

### ISSUE THREAD

**Issue by evolify** [remarkjs/remark-gfm#2]
Some url text rendered to link incorrect，the text after url will included to the link, how to disable autolink?

**Comment by wooorm** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
