### ISSUE TITLE
Lazy list/blockquote breaks container w/ `remark-gfm`

### ISSUE THREAD

**Issue by blattersturm** [remarkjs/remark-gfm#3]
### Subject of the issue

With the `remark-gfm` plugin enabled, in a list indented with 4 characters, a HTML tag with a 3-character indent will split up the list.

### Your environment

Happens on astexplorer.net too.

### Steps to reproduce

```
1.  Hello
2.  World
   <br>Manual break!
3.  Ouch.
```

### Expected behavior

No paragraph is generated, the list is entirely complete (as happens with the GFM plugin disabled).

### Actual behavior

The `<br>` and onwards signal the end of the list, and entry `3.` will be a plain text in a paragraph.

(edited by wooorm to fix markdown)

**Comment by wooorm** [comment]
It doesn’t seem related to the tag:

```
1.  Hello
2.  World
   c
3.  Ouch.
```

Does the same

**Comment by wooorm** [comment]
thanks for reporting, @blattersturm. Might have to do with checkboxes because that’s a GFM feature relating to lists... 🤔 Or maybe it’s tables being annoying again

**Comment by blattersturm** [comment]
It appears to be tables, indeed.

**Comment by gilisho** [comment]
I have another example rather than #9, which might be related to this issue as well.

Take this markdown for instance:
```
> **Note:**
>
> Hello
text supposed to be on the same line but isn't
>
> oh no
>
> the end
```
Github renders this as:
> **Note:**
>
> Hello
text supposed to be on the same line but isn't
>
> oh no
>
> the end

but the output in `remark-gfm` is: 
![image](https://user-images.githubusercontent.com/40733156/109657538-45a51d80-7b6e-11eb-8534-6725877214f8.png)


https://codesandbox.io/s/react-markdown-forked-9q50f?file=/src/App.js

Anything we can do to help in order to get the fix as soon as possible? This is happening in a lot of markdowns since it relates to almost every component which is sort of "indented",  so I think this should be in highest priority.

**Comment by wooorm** [comment]
> Anything we can do to help in order to get the fix as soon as possible?

It is not currently my priority. It is incredibly complex. Standard markdown is line based, so micromark is line based and set up as streaming for its parsing. GFM breaks that, so it means flipping the architecture.

> I think this should be in highest priority.

PR == welcome!

**Comment by talentedandrew** [comment]
Is this issue fixed? I'm having the same issue with `react-markdown@6.0.3` and `react-gfm@1.0.0`.

**Comment by wooorm** [comment]
Yes, see the commit that closes this. You are having problems because you’re on old packages. You should update.

**Comment by talentedandrew** [comment]
Yes, I did see the commit and it fixes the problem, but I have an old package. But I just can't update it since its a monorepo(both frontend and backend in the same repo) and a legacy project. Can you suggest any other alternative to fix this while using the react-markdown@6.0.3 and react-gfm@1.0.0 ?

**Comment by wooorm** [comment]
There is no alternative.

**Comment by paul-mcnamee** [comment]
> There is no alternative.

I solved it with css:

```css

  ol {
    list-style: none;
    counter-reset: orderedListCounter;
  }
  ol li {
    counter-increment: orderedListCounter;
  }
  ol li::before {
    content: counter(orderedListCounter) '. ';
    font-weight: bold;
  }
```
